SHOW timezone;

SELECT now();

CREATE TABLE timeZ (ts TIMESTAMP WITHOUT TIME ZONE, tsz TIMESTAMP WITH TIME ZONE);

INSERT INTO timez VALUES ('2024-01-12 10:45:00','2024-01-12 10:45:00');

SELECT * FROM timez;

SELECT now();

SELECT CURRENT_DATE;

SELECT now()::DATE;

SELECT now()::TIME;