SHOW timezone;

SELECT now();

CREATE TABLE timeZ (ts TIMESTAMP WITHOUT TIME ZONE, tsz TIMESTAMP WITH TIME ZONE);

INSERT INTO timez VALUES ('2024-01-12 10:45:00','2024-01-12 10:45:00');

SELECT * FROM timez;

SELECT now();

SELECT CURRENT_DATE;

SELECT now()::DATE;

SELECT now()::TIME;

SELECT to_char(now(),'DD/MM/YYYY');

SELECT CURRENT_DATE - INTERVAL '1 MONTH';

SELECT age(CURRENT_DATE, '1996-07-29');

SELECT * FROM students;

SELECT * ,age(CURRENT_DATE,dob) FROM students;

SELECT extract(year,'2024-01-25');

SELECT extract(MONTH FROM '2024-01-25'::DATE);